# Generated by Django 3.2.4 on 2021-07-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
