# Generated by Django 3.2.4 on 2021-07-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='seccion',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_seccion', to='shop.seccion'),
            preserve_default=False,
        ),
    ]
